blog2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('grappelli/',include('grappelli.urls')), #grappelli urls
    path('admin/', admin.site.urls),
    path('',include('user.urls')),
    path('',include('comments.urls')),
    path('search/', include('haystack.urls')),
]

comments/urls.py
from django.urls import path
from . import views
app_name = 'comments'
urlpatterns = [
    path('comment/post/<pk>/',views.post_comment,name='post_comment'),
]

user/urls.py
from django.urls import path
from user import views
from user.feeds import ALLPostsRssFeed
# 视图函数命名空间
app_name = 'user'
urlpatterns = [
    path('', views.IndexView.as_view(),name='index'),
    #/post/1/
    path('post/<pk>/',views.PostDetailView.as_view(),name='detail'),
    path('archives/<year>/<month>/',views.ArchivesView.as_view(),name='archives'),
    path('category/<pk>/',views.CategoryView.as_view(),name='category'),
    path('tag/<pk>/',views.TagView.as_view(),name = 'tag'),
    path('all/rss/',ALLPostsRssFeed(),name='rss'),
    # path('search/',views.search,name = 'search'),
]

comments/models.py
from django.db import models
from user.models import Post

# Create your models here.
class Comment(models.Model):
    class Meta:
        db_table='comment'
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]

user/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.urls import reverse
import markdown
#摘要获取
from django.utils.html import strip_tags

class Category(models.Model):
    class Meta:
        db_table = 'category'
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Tag(models.Model):
    class Meta:
        db_table = 'tag'
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    class Meta:
        db_table = 'post'
        ordering = ['-created_time']
    title = models.CharField(max_length=70)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200,blank=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag,blank=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.title

# 从django.urls 中导入reverse函数,将pk传入url
    def get_absolute_url(self):
        return reverse('user:detail',kwargs={'pk':self.pk})
    # 新增views字段记录阅读量
    views = models.PositiveIntegerField(default=0)
    # 每调用一次views数值+1
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    # 自动提取文章前54个字符为摘要
    def save(self,*args,**kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.body))[:54] + '......'

        super(Post,self).save(*args,**kwargs)

templates/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <title>loge的博客</title>
    <style>
        span.highlighted{
            color:red;
        }
    </style>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/highlights/github.css' %}">

    <!-- js -->
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'user:index' %}"><b>Loge</b> &amp; blog</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'user:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'user:index' %}" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name='q' placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}

                        <li>
                            <a href="{{ post.get_absolute_url }}">{{post.title}}</a>
                        </li>
                        {% empty %}
                            暂无文章
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        {% archives as date_lists %}
                        <li>
                            {% for date in date_lists %}

                            <a href="{% url 'user:archives' date.year date.month %}">{{date.year}}年{{ date.month }}月</a>
                        </li>
                        {% empty %}
                                暂无归档
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        {% get_categories as categories_list %}
                        <li>
                            {% for category in categories_list %}

                            <a href="{% url 'user:category' category.pk %}">{{category}} <span class="post-count">({{category.num_posts}})</span></a>
                        </li>
                        {% empty %}
                            暂无分类
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% get_tags as tag_list %}
                            {% for tag in tag_list %}
                            <li><a href="{% url 'user:tag' tag.pk %}">{{ tag }}<span class="post-count">({{tag.num_posts}})</span></a></li>
                            {% empty %}
                                暂无标签！
                            {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'user:rss' %}'"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2018-2019 Loge&blog
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block main %}
        {% if error_msg %}
            <p style="color: red">{{ error_msg }}</p>
        {% endif %}
            {% for post in post_list %}

            <article class="post post-{{ post.pk }}">
                <header class="entry-header">
                    <h1 class="entry-title">
                        <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                    </h1>
                    <div class="entry-meta">
                        <span class="post-category"><a href="{% url 'user:category' post.category_id %}">{{post.category}}</a></span>
                        <span class="post-date"><a href="#"><time class="entry-date"
                                                                  datetime="{{post.created_time}}">{{ post.created_time }}</time></a></span>
                        <span class="post-author"><a href="#">{{ post.author }}</a></span>
                        <span class="comments-link"><a href="{% url 'user:detail' post.pk %}">{{ post.comment_set.count }} 评论</a></span>
                        <span class="views-count"><a href="{% url 'user:detail' post.pk %}">{{post.views}} 阅读</a></span>
                    </div>
                </header>
                <div class="entry-content clearfix">
                    <p>{{post.excerpt}}</p>
                    <div class="read-more cl-effect-14">
                        <a href="{{post.get_absolute_url}}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                    </div>
                </div>
            </article>
            {% empty %}
                <div class="no-post">暂时还没有文章！</div>
            {% endfor %}
            {% if is_paginated %}
                <div class="text-center">
                <div class="pagination">
                {% if first %}
                    <a href="?page=1">1</a>
                {% endif %}
                {% if left %}
                    {% if left_has_more %}
                        <span>...</span>
                    {% endif %}
                    {% for i in left %}
                        <a href="?page={{ i }}">{{ i }}</a>
                    {% endfor %}
                {% endif %}
                <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
                {% if right %}
                    {% for i in right %}
                        <a href="?page={{ i }}">{{ i }}</a>
                    {% endfor %}
                    {% if right_has_more %}
                        <span>...</span>
                    {% endif %}
                {% endif %}
                {% if last %}
                    <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                {% endif %}
                </div>
                </div>
            {% endif %}
{% endblock main %}

templates/single.html
<!DOCTYPE html>
{% extends 'base.html'%}
{% block main %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{post.title}}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{post.created_time}}">{{post.created_time}}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{post.views}} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{post.body|safe}}</p>
                        <div class="widget-tag-cloud">
                            <ul>
                                标签:
                                {% for tag in post.tag.all %}
                                    <li><a href="{% url 'user:tag' tag.pk %}">{{ tag }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="id_name">名字：</label>
                                {{ form.name }}
                                {{ form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="id_email">邮箱：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="id_url">网址：</label>
                                {{ form.url }}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-12">
                                <label for="id_comment">评论：</label>
                                {{ form.text }}
                                {{ form.text.errors }}
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>4</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}

                            <li class="comment-item">
                                <span class="nickname">{{comment.name}}</span>
                                <time class="submit-date" datetime="{{comment.created_time}}">{{comment.created_time}}</time>
                                <div class="text">
                                    {{ comment.text }}
                                </div>
                            </li>
                            {% empty %}
                            暂无评论
                            {% endfor %}
                        </ul>
                    </div>
                </section>
{% endblock main %}
{% block toc %}
                <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    {{ post.toc|safe }}
                </div>
{% endblock toc %}
<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
        </ul>
    </nav>
</div>

<script src="js/script.js"></script>